title: localde çalışıyordu
description: Yazılım/Programlama grubundan haftalık haber bülteni
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/Bilgisayar-Kavramlari-Toplulugu/localde-calisiyordu" 
markdown: kramdown
# theme: minima # Removed to use custom layouts exclusively.
plugins:
  - jekyll-feed
exclude:
  - post-template.html
  - post-template.md
  - LICENSE
  - README.md
