title: localde çalışıyordu
description: Yazılım/Programlama grubundan haftalık haber bülteni
baseurl: "/localde-calisiyordu" # subpath on GitHub Pages
url: "https://bilgisayar-kavramlari-toplulugu.github.io"
markdown: kramdown
# theme: minima # Removed to use custom layouts exclusively.
plugins:
  - jekyll-feed
exclude:
  - post-template.html
  - post-template.md
  - LICENSE
  - README.md
